services:
  mariadb:
    image: mariadb:lts
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_DATABASE: "${DB_DATABASE}"
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su=mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: matzeds/cookbook-backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
      SECRET_KEY: "${SECRET_KEY}"
    volumes:
      - ./backend/cookbook:/app/cookbook

  frontend:
    image: matzeds/cookbook-frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      PMA_HOST: "mariadb"
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASSWORD}"

volumes:
  data:
