services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_DATABASE: "${DB_DATABASE}"
    volumes:
      - ./data:/var/lib/mysql

  backend:
    image: matzeds/cookbook-backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_DATABASE}?charset=utf8mb4'

  frontend:
    image: matzeds/cookbook-frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"